# Generated by Django 3.1 on 2023-03-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w3school_sql', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
