# Generated by Django 3.1 on 2023-03-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3school_sql', '0003_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='PostalCode',
            field=models.CharField(max_length=50),
        ),
    ]
