# Generated by Django 3.1 on 2023-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3school_sql', '0004_auto_20230312_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('CategoryName', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('LastName', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('BirthDate', models.DateField()),
                ('Photo', models.ImageField(upload_to='emp_img')),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('ShipperID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ShipperName', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('SupplierName', models.CharField(max_length=100)),
                ('ContactName', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('PostalCode', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
