# Generated by Django 3.1 on 2023-03-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w3school_sql', '0005_auto_20230312_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shippers',
            new_name='Shipper',
        ),
        migrations.RenameModel(
            old_name='Suppliers',
            new_name='Supplier',
        ),
    ]
