# Generated by Django 3.1 on 2023-03-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w3school_sql', '0006_auto_20230312_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ProductName', models.CharField(max_length=100)),
                ('Unit', models.IntegerField()),
                ('Price', models.PositiveIntegerField()),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w3school_sql.category')),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w3school_sql.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w3school_sql.customer')),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w3school_sql.employee')),
                ('ShipperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w3school_sql.shipper')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('OrderDetailID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Quantity', models.IntegerField()),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w3school_sql.orders')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w3school_sql.products')),
            ],
        ),
    ]
