# Generated by Django 3.1 on 2023-03-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w3school_sql', '0007_orderdetails_orders_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
