# Generated by Django 3.1 on 2020-08-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaamkaj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kaamkaj',
            old_name='accomplished',
            new_name='complete_date',
        ),
        migrations.AddField(
            model_name='kaamkaj',
            name='active',
            field=models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2),
        ),
        migrations.AddField(
            model_name='kaamkaj',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
