# Generated by Django 3.0.4 on 2020-03-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200311_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterlookup',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='master_data',
        ),
        migrations.RemoveField(
            model_name='socialmedialink',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usereducation',
            name='broad_stream',
        ),
        migrations.RemoveField(
            model_name='usereducation',
            name='type_of_degree',
        ),
        migrations.RemoveField(
            model_name='usereducation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userwork',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='userwork',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=0),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='MasterLookUp',
        ),
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
        migrations.DeleteModel(
            name='UserEducation',
        ),
        migrations.DeleteModel(
            name='UserVerification',
        ),
        migrations.DeleteModel(
            name='UserWork',
        ),
    ]
